; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	\\ahs\ahsfiles\Users\AHS-CO\Steven.Ulfelder\Personal Projects\Shoshin\Shoshin\src\ext.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?myglfunc@@3PAPAXA				; myglfunc
_BSS	SEGMENT
?myglfunc@@3PAPAXA DD 05H DUP (?)			; myglfunc
_BSS	ENDS
PUBLIC	?EXT_Init@@YIXXZ				; EXT_Init
PUBLIC	??_C@_0BH@BOJGDFJN@glCreateShaderProgramv?$AA@	; `string'
PUBLIC	??_C@_0BG@CCBKOCA@glGenProgramPipelines?$AA@	; `string'
PUBLIC	??_C@_0BG@GLPOKNCG@glBindProgramPipeline?$AA@	; `string'
PUBLIC	??_C@_0BD@CADKHDMH@glUseProgramStages?$AA@	; `string'
PUBLIC	??_C@_0BE@KBMHINLC@glProgramUniform4fv?$AA@	; `string'
EXTRN	__imp__wglGetProcAddress@4:PROC
;	COMDAT ??_C@_0BE@KBMHINLC@glProgramUniform4fv?$AA@
CONST	SEGMENT
??_C@_0BE@KBMHINLC@glProgramUniform4fv?$AA@ DB 'glProgramUniform4fv', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@CADKHDMH@glUseProgramStages?$AA@
CONST	SEGMENT
??_C@_0BD@CADKHDMH@glUseProgramStages?$AA@ DB 'glUseProgramStages', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@GLPOKNCG@glBindProgramPipeline?$AA@
CONST	SEGMENT
??_C@_0BG@GLPOKNCG@glBindProgramPipeline?$AA@ DB 'glBindProgramPipeline', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@CCBKOCA@glGenProgramPipelines?$AA@
CONST	SEGMENT
??_C@_0BG@CCBKOCA@glGenProgramPipelines?$AA@ DB 'glGenProgramPipelines', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@BOJGDFJN@glCreateShaderProgramv?$AA@
CONST	SEGMENT
??_C@_0BH@BOJGDFJN@glCreateShaderProgramv?$AA@ DB 'glCreateShaderProgramv'
	DB	00H						; `string'
CONST	ENDS
glstrs	SEGMENT
?strs@@3PAPADA DD FLAT:??_C@_0BH@BOJGDFJN@glCreateShaderProgramv?$AA@ ; strs
	DD	FLAT:??_C@_0BG@CCBKOCA@glGenProgramPipelines?$AA@
	DD	FLAT:??_C@_0BG@GLPOKNCG@glBindProgramPipeline?$AA@
	DD	FLAT:??_C@_0BD@CADKHDMH@glUseProgramStages?$AA@
	DD	FLAT:??_C@_0BE@KBMHINLC@glProgramUniform4fv?$AA@
glstrs	ENDS
; Function compile flags: /Ogspy
; File \\ahs\ahsfiles\users\ahs-co\steven.ulfelder\personal projects\shoshin\shoshin\src\ext.cpp
;	COMDAT ?EXT_Init@@YIXXZ
extinit	SEGMENT
?EXT_Init@@YIXXZ PROC					; EXT_Init, COMDAT

; 26   : {

	push	esi

; 27   :     for( int i=0; i<NUMFUNCIONES; i++ )

	xor	esi, esi
$LL4@EXT_Init:

; 28   : 		myglfunc[i] = wglGetProcAddress( strs[i] );

	push	DWORD PTR ?strs@@3PAPADA[esi]
	call	DWORD PTR __imp__wglGetProcAddress@4
	mov	DWORD PTR ?myglfunc@@3PAPAXA[esi], eax
	add	esi, 4
	cmp	esi, 20					; 00000014H
	jl	SHORT $LL4@EXT_Init
	pop	esi

; 29   : }

	ret	0
?EXT_Init@@YIXXZ ENDP					; EXT_Init
extinit	ENDS
END
